---
# Comon variables
run_as_docker: false
# network_interface which is used to connect to nodes. Required
network_interface: enp0s8

# Geth variables
## Geth version
geth_version: "1.13.9"

datadir: /mnt/geth
networkid: 1337

geth_accounts:
  # name is used to identify the account and must be unique
  - name: default # required account
    node: node1
    create: true
    # address must be speicifed if password is not empty
    address: ""
    # password must be speicifed if address is not empty. If create is true and password
    # is empty, a random password will be generated.
    password: ""
    balance: 10000000000000000 # optional
    # the content of the secret file in JSON format
    secret_content: ""
    # miner is optional, if set to true, the account will be used as miner
    miner: true
  # name is used to identify the account and must be unique
  - name: default # required account
    node: node2
    create: true
    # address must be speicifed if password is not empty
    address: ""
    # password must be speicifed if address is not empty. If create is true and password
    # is empty, a random password will be generated.
    password: ""
    balance: 10000000000000000 # optional
    # the content of the secret file in JSON format
    secret_content: ""
    # miner is optional, if set to true, the account will be used as miner
    miner: false

# Bootnode variables
## bootnode is the hostname of the bootnode
bootnode_on_host: "node1"
## bootnode_ip_addr is the IP address of the bootnode. This ip must be accessible from all nodes. Required
bootnode_ip_addr: ""

# Wipe variables
wipe: false
wipe_target: "data,genesis"

# Ingress varialbes
ingress:
  # lb_method nginx load-balance method. Details: https://docs.nginx.com/nginx/admin-guide/load-balancer/http-load-balancer/
  lb_method: ""
  domain_name: geth.example.com
  ssl:
    # when enabled is true, cert and key must be specified
    enabled: false
    base64_cert: ""
    base64_key: ""
