---
- name: restart bootnode
  systemd:
    name: bootnode
    daemon_reload: true
    state: restarted
    enabled: true

- name: restart geth
  systemd:
    name: geth
    daemon_reload: true
    enabled: true
    state: restarted
