---
- name: Install Lighthouse
  when: not (run_as_docker | default(false) | bool)
  args:
    executable: /bin/bash
  shell: |
    if ! command -v lighthouse &> /dev/null; then
      mkdir -p /tmp/lighthouse && \
        curl -SL https://github.com/sigp/lighthouse/releases/download/v${LIGHTHOUSE_VERSION}/lighthouse-v${LIGHTHOUSE_VERSION}-${ARCH}-unknown-${OS}-gnu.tar.gz | \
        tar -xvz -C /tmp/lighthouse && \
        mv /tmp/lighthouse/lighthouse /usr/local/bin && \
        rm -rf /tmp/lighthouse
    fi
  environment:
    LIGHTHOUSE_VERSION: "{{lighthouse_version}}"
    OS: "{{ansible_system|lower}}"
    ARCH: "{{ansible_architecture}}"

- name: Render Lighthouse template
  template:
    src: templates/lighthouse.service.j2
    dest: /etc/systemd/system/lighthouse.service
    owner: root
    group: root
    mode: 0644
  notify: restart lighthouse
