---
- name: Update apt packages
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install required packages
  apt:
    name: "{{item}}"
    state: present
  loop:
    - jq
    - curl
    - tar
    - git
    - libssl-dev
# - name: Check miner
#   shell: echo "miner $NODE_NAME is running"
#   environment:
#     NODE_NAME: "{{inventory_hostname}}"
#   when: miner is defined and miner == true
