---
- name: Add Docker GPG apt-key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repositoty
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install python3-docker to satisfy ansible requirement
  apt:
    name: python3-docker
    state: present

- name: Install docker-ce package
  apt:
    name: docker-ce
    state: present

- name: Handle Docker Daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: 0644
  notify: restart docker

- name: Ensure that docker has started
  systemd:
    name: docker
    state: started
    enabled: true

- name: Refresh facts until ansible_docker0 is available
  setup:
  until: ansible_docker0 is defined
  delay: 1
  retries: 5

- name: Handle docker-pruner systemd service file
  template:
    src: docker-pruner.service.j2
    dest: /etc/systemd/system/docker-pruner.service
    owner: root
    group: root
    mode: 0644
  notify: restart docker-pruner timer

- name: Handle docker-pruner systemd timer file
  template:
    src: docker-pruner.timer.j2
    dest: /etc/systemd/system/docker-pruner.timer
    owner: root
    group: root
    mode: 0644
  notify: restart docker-pruner timer

- name: Ensure that docker-pruner timer has been started and enabled
  systemd:
    name: docker-pruner.timer
    state: started
    enabled: yes
    daemon_reload: true
